shellEmulator: true

trustPolicy: no-downgrade

overrides:
  "@tiptap/core": 3.13.0
  "@tiptap/extension-blockquote": 3.13.0
  "@tiptap/extension-bold": 3.13.0
  "@tiptap/extension-code": 3.13.0
  "@tiptap/extension-code-block": 3.13.0
  "@tiptap/extension-collaboration": 3.13.0
  "@tiptap/extension-document": 3.13.0
  "@tiptap/extension-hard-break": 3.13.0
  "@tiptap/extension-heading": 3.13.0
  "@tiptap/extension-italic": 3.13.0
  "@tiptap/extension-link": 3.13.0
  "@tiptap/extension-list": 3.13.0
  "@tiptap/extension-node-range": 3.13.0
  "@tiptap/extension-paragraph": 3.13.0
  "@tiptap/extension-strike": 3.13.0
  "@tiptap/extension-text": 3.13.0
  "@tiptap/extension-underline": 3.13.0
  "@tiptap/extension-drag-handle": 3.13.0
  "@tiptap/extensions": 3.13.0
  "@tiptap/pm": 3.13.0
ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
  - vue-demi
